name: Build Watch App

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict --quiet

      - name: Install CocoaPods
        run: |
          brew install cocoapods || true
          pod install || true
        working-directory: frontend

      - name: Build Watch App
        run: |
          xcodebuild -scheme WavelengthWatchApp \
                     -sdk watchos \
                     -configuration Debug \
                     -destination 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)' \
                     build
        working-directory: frontend
