name: Frontend (watchOS) CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  lint-and-build:
    runs-on: macos-14
    env:
      PROJECT_PATH: frontend/WavelengthWatchApp.xcodeproj
      SCHEME: WavelengthWatchApp Watch App
      DEVELOPER_DIR: /Applications/Xcode_16.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use Xcode 16, which includes the watchOS 11 SDK.
      - name: Select Xcode 16
        run: |
          set -euo pipefail
          sudo xcode-select -s "$DEVELOPER_DIR"
          xcodebuild -version
          xcrun simctl list runtimes

      - name: Set up Python (for pre-commit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install SwiftLint and pre-commit
        run: |
          brew install swiftlint
          pip install --upgrade pre-commit

      # Runs your full pre-commit suite (Python + SwiftLint). Make sure your
      # .pre-commit-config.yaml uses: `swiftlint lint --strict` and points at the same config CI uses.
      - name: Run pre-commit (strict)
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Verify shared scheme exists
        run: |
          set -euo pipefail
          xcodebuild -list -project "$PROJECT_PATH"
          if [ ! -f "$PROJECT_PATH/xcshareddata/xcschemes/${SCHEME}.xcscheme" ]; then
            echo "::warning::Shared scheme '${SCHEME}' not found at '$PROJECT_PATH/xcshareddata/xcschemes/'. Open Xcode → Product → Scheme → Manage Schemes… and check 'Shared'."
          fi

      - name: Show available watchOS destinations
        run: |
          xcodebuild -project "$PROJECT_PATH" \
            -scheme "$SCHEME" \
            -showdestinations

      # Build the watch-only app for the watchOS Simulator in Debug.
      - name: Build (Debug)
        run: |
          set -euo pipefail
          xcodebuild \
            -project frontend/WavelengthWatchApp.xcodeproj \
            -scheme "WavelengthWatchApp Watch App" \
            -configuration Debug \
            -sdk watchsimulator \
            -destination "generic/platform=watchOS Simulator" \
            CODE_SIGNING_ALLOWED=NO \
            clean build | tee build-debug.log

      - name: Build (Release)
        run: |
          set -euo pipefail
          xcodebuild \
            -project frontend/WavelengthWatchApp.xcodeproj \
            -scheme "WavelengthWatchApp Watch App" \
            -configuration Release \
            -sdk watchsimulator \
            -destination "generic/platform=watchOS Simulator" \
            CODE_SIGNING_ALLOWED=NO \
            clean build | tee build-release.log

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: watchos-build-logs
          path: |
            build-debug.log
            build-release.log
